AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda + Typescript Starter Project

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  # Environmentのincludeが可能
  # Defaultが値でTypeが変数の型
  DynamoDBEndpoint:
    Type: String
    Description: DynamoDB Endpoint
    Default: http://docker.for.mac.localhost:8000
  Region:
    Type: String
    Description: AWS Deploy Region
    Default: ap-northeast-1
  S3Path:
    Type: String
    Default: example-lambda-1634779516

Resources:
  CommonResourcesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: commonResourcesLayer
      Description: Common Resource Layer
      ContentUri: src/layers/commonResourcesLayer/dist
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
  Greeting:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/app/greeting/dist
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: !Ref DynamoDBEndpoint
          REGION: !Ref Region
      Layers:
        - !Ref CommonResourcesLayer
      Events:
        App:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /app/greeting
            Method: get

  NotificationsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/app/appsync/dist
      Runtime: nodejs12.x
      Timeout: 10
      MemorySize: 256
      Handler: appsync.handler